<a href="https://colab.research.google.com/github/libishm1/pcd_transforms/blob/main/edition3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install open3d

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 399.7/399.7 MB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 24.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.4/139.4 kB 17.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 28.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 28.1 MB/s eta 0:00:00
  Attempting uninstall: widgetsnbextension
    Found existing installation: widgetsnbextension 3.6.6
    Uninstalling widgetsnbextension-3.6.6:
      Successfully uninstalled widgetsnbextension-3.6.6
  Attempting uninstall: ipywidgets
    Found existing installation: ipywidgets 7.7.1
    Uninstalling ipywidgets-7.7.1:
      Successfully uninstalled ipywidgets-7.7.1


In [9]:
import numpy as np
import math

# Convert degrees to radians
def deg_to_rad(deg):
    return math.radians(deg)

# Euler angles to rotation matrix (ZYX order)
def euler_to_rotation(roll, pitch, yaw):
    R_x = np.array([[1, 0, 0],
                     [0, math.cos(roll), -math.sin(roll)],
                     [0, math.sin(roll), math.cos(roll)]])

    R_y = np.array([[math.cos(pitch), 0, math.sin(pitch)],
                     [0, 1, 0],
                     [-math.sin(pitch), 0, math.cos(pitch)]])

    R_z = np.array([[math.cos(yaw), -math.sin(yaw), 0],
                     [math.sin(yaw), math.cos(yaw), 0],
                     [0, 0, 1]])

    R = np.dot(R_z, np.dot(R_y, R_x))
    return R

# List of robot poses
robot_poses = [
    ((800.093, 120.964, 113), (36, -4, -96)),
    ((652.191, 237.421, 113), (72, -4, -90)),
    ((321.472, 129.964, 113), (144, -4, -90)),
    ((321.472, -217.774, 113), (-144, -4, -90)),
    ((469.374, -325.231, 113), (-108, -4, -90)),
    ((652.191, -325.231, 113), (-72, -4, -90)),
    ((800.093, -217.774, 113), (-36, -4, -90)),
    ((789.607, 122.346, 163), (36, -18, -90)),
    ((648.185, 225.094, 163), (72, -18, -90)),
    ((473.379, 225.094, 163), (108, -18, -90)),
    ((331.958, 122.346, 163), (144, -18, -90)),
    ((277.939, -43.905, 163), (-180, -18, -90)),
    ((331.958, -210.156, 163), (-144, -18, -90)),
    ((473.379, -312.904, 163), (-108, -18, -90)),
    ((789.607, -210.156, 163), (-36, -18, -90)),
    ((802.489, -43.905, 238), (0, -41.5, -90)),
    ((820.59, -43.905, 213), (0, -33, -90)),
    ((770.971, 108.806, 213), (36, -33, -90)),
    ((641.067, 203.187, 213), (72, -33, -90)),
    ((480.497, 203.187, 213), (108, -33, -90)),
    ((350.593, 108.806, 213), (144, -33, -90)),
    ((300.974, -43.905, 213), (-180, -33, -90)),
    ((350.593, -196.616, 213), (-144, -33, -90)),
    ((480.497, -290.997, 213), (-108, -33, -90)),
    ((641.067, -290.997, 213), (-72, -33, -90)),
    ((770.971, -196.616, 213), (-36, -33, -90))
]

# Convert each pose to a transformation matrix
for pose in robot_poses:
    # Convert Euler angles to radians
    roll, pitch, yaw = map(deg_to_rad, pose[1])

    # Compute rotation matrix
    R = euler_to_rotation(roll, pitch, yaw)

    # Translation vector
    T = np.array([[pose[0][0]], [pose[0][1]], [pose[0][2]]])

    # Combine rotation and translation to form transformation matrix
    T_matrix = np.vstack((np.hstack((R, T)), [0, 0, 0, 1]))

    print("Transformation Matrix for Pose:", pose)
    print(T_matrix)
    print()


Transformation Matrix for Pose: ((800.093, 120.964, 113), (36, -4, -96))
[[-1.04273837e-01  8.08870973e-01 -5.78666326e-01  8.00093000e+02]
 [-9.92099290e-01 -4.37880890e-02  1.17565310e-01  1.20964000e+02]
 [ 6.97564737e-02  5.86353437e-01  8.07046270e-01  1.13000000e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Transformation Matrix for Pose: ((652.191, 237.421, 113), (72, -4, -90))
[[ 6.10831811e-17  3.09016994e-01 -9.51056516e-01  6.52191000e+02]
 [-9.97564050e-01  6.63423489e-02  2.15559359e-02  2.37421000e+02]
 [ 6.97564737e-02  9.48739790e-01  3.08264245e-01  1.13000000e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Transformation Matrix for Pose: ((321.472, 129.964, 113), (144, -4, -90))
[[ 6.10831811e-17 -8.09016994e-01 -5.87785252e-01  3.21472000e+02]
 [-9.97564050e-01  4.10018265e-02 -5.64341727e-02  1.29964000e+02]
 [ 6.97564737e-02  5.86353437e-01 -8.07046270e-01  1.13000000e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00

In [10]:
# Define a list of point cloud file paths
point_cloud_files = [
    "/content/drive/MyDrive/clouds/1.xyz",
    "//content/drive/MyDrive/clouds/2.xyz",
    #"/content/drive/MyDrive/clouds/3.xyz",
    "//content/drive/MyDrive/clouds/4.xyz",
    #"/content/drive/MyDrive/clouds/5.xyz",
    "//content/drive/MyDrive/clouds/6.xyz",
    "/content/drive/MyDrive/clouds/7.xyz",
    "//content/drive/MyDrive/clouds/8.xyz",
    "/content/drive/MyDrive/clouds/9.xyz",
   # "//content/drive/MyDrive/clouds/10.xyz",
    "/content/drive/MyDrive/clouds/11.xyz",
    "//content/drive/MyDrive/clouds/12.xyz",
    "/content/drive/MyDrive/clouds/13.xyz",
    "//content/drive/MyDrive/clouds/14.xyz",
    "/content/drive/MyDrive/clouds/15.xyz",
    "//content/drive/MyDrive/clouds/16.xyz",
    "/content/drive/MyDrive/clouds/17.xyz",
    #"//content/drive/MyDrive/clouds/18.xyz",
    "/content/drive/MyDrive/clouds/19.xyz",
    "//content/drive/MyDrive/clouds/20.xyz",
    "/content/drive/MyDrive/clouds/21.xyz",
    "//content/drive/MyDrive/clouds/22.xyz",
    "/content/drive/MyDrive/clouds/23.xyz",
    "//content/drive/MyDrive/clouds/24.xyz",
    "/content/drive/MyDrive/clouds/25.xyz",
    "//content/drive/MyDrive/clouds/26.xyz",
    "/content/drive/MyDrive/clouds/27.xyz",
    "//content/drive/MyDrive/clouds/28.xyz",
    "/content/drive/MyDrive/clouds/29.xyz",
    "//content/drive/MyDrive/clouds/30.xyz",
     ]

In [17]:
import open3d as o3d
import numpy as np
import math

# Convert degrees to radians
def deg_to_rad(deg):
    return math.radians(deg)

# Euler angles to rotation matrix (ZYX order)
def euler_to_rotation(roll, pitch, yaw):
    R_x = np.array([[1, 0, 0],
                     [0, math.cos(roll), -math.sin(roll)],
                     [0, math.sin(roll), math.cos(roll)]])

    R_y = np.array([[math.cos(pitch), 0, math.sin(pitch)],
                     [0, 1, 0],
                     [-math.sin(pitch), 0, math.cos(pitch)]])

    R_z = np.array([[math.cos(yaw), -math.sin(yaw), 0],
                     [math.sin(yaw), math.cos(yaw), 0],
                     [0, 0, 1]])

    R = np.dot(R_z, np.dot(R_y, R_x))
    return R

# Inverse rotation matrix
def inverse_rotation_matrix(R):
    return np.linalg.inv(R)

# Apply inverse rotation and translation to point cloud
def inverse_transform_point_cloud(point_cloud, R_inv, t):
    # Convert point cloud to Open3D format
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(point_cloud)

    # Apply inverse rotation
    pcd.rotate(R_inv, center=(0, 0, 0))

    # Apply inverse translation
    pcd.translate(-t)

    # Get transformed point cloud as NumPy array
    transformed_points = np.asarray(pcd.points)

    return transformed_points

# Load point clouds using Open3D and convert them to NumPy arrays
def load_and_convert_point_clouds(point_cloud_files):
    point_clouds = []
    for file in point_cloud_files:
        pcd = o3d.io.read_point_cloud(file)
        points = np.asarray(pcd.points)
        point_clouds.append(points)
    return point_clouds

consecutive_poses = [
    ((np.array([800.093, 120.964, 113]), (36, -4, -96)), "/content/drive/MyDrive/clouds/1.xyz"),
    ((np.array([652.191, 237.421, 113]), (72, -4, -90)), "/content/drive/MyDrive/clouds/2.xyz"),
    ((np.array([469.374, 237.421, 113]), (108, -4, -90)), "/content/drive/MyDrive/clouds/3.xyz"),
    ((np.array([321.472, 129.964, 113]), (144, -4, -90)), "/content/drive/MyDrive/clouds/4.xyz"),
    ((np.array([264.978, -43.905, 113]), (-180, -4, -90)), "/content/drive/MyDrive/clouds/5.xyz"),
    ((np.array([321.472, -217.774, 113]), (-144, -4, -90)), "/content/drive/MyDrive/clouds/6.xyz"),
    ((np.array([469.374, -325.231, 113]), (-108, -4, -90)), "/content/drive/MyDrive/clouds/7.xyz"),
    ((np.array([652.191, -325.231, 113]), (-72, -4, -90)), "/content/drive/MyDrive/clouds/8.xyz"),
    ((np.array([800.093, -217.774, 113]), (-36, -4, -90)), "/content/drive/MyDrive/clouds/9.xyz"),
    ((np.array([843.625, -43.905, 163]), (0, -18, -90)), "/content/drive/MyDrive/clouds/10.xyz"),
    ((np.array([789.607, 122.346, 163]), (36, -18, -90)), "/content/drive/MyDrive/clouds/11.xyz"),
    ((np.array([648.185, 225.094, 163]), (72, -18, -90)), "/content/drive/MyDrive/clouds/12.xyz"),
    ((np.array([473.379, 225.094, 163]), (108, -18, -90)), "/content/drive/MyDrive/clouds/13.xyz"),
    ((np.array([331.958, 122.346, 163]), (144, -18, -90)), "/content/drive/MyDrive/clouds/14.xyz"),
    ((np.array([277.939, -43.905, 163]), (-180, -18, -90)), "/content/drive/MyDrive/clouds/15.xyz"),
    ((np.array([331.958, -210.156, 163]), (-144, -18, -90)), "/content/drive/MyDrive/clouds/16.xyz"),
    ((np.array([473.379, -312.904, 163]), (-108, -18, -90)), "/content/drive/MyDrive/clouds/17.xyz"),
    ((np.array([648.185, -312.904, 163]), (-72, -18, -90)), "/content/drive/MyDrive/clouds/18.xyz"),
    ((np.array([789.607, -210.156, 163]), (-36, -18, -90)), "/content/drive/MyDrive/clouds/19.xyz"),
    ((np.array([802.489, -43.905, 238]), (0, -41.5, -90)), "/content/drive/MyDrive/clouds/20.xyz"),
    ((np.array([820.59, -43.905, 213]), (0, -33, -90)), "/content/drive/MyDrive/clouds/21.xyz"),
    ((np.array([770.971, 108.806, 213]), (36, -33, -90)), "/content/drive/MyDrive/clouds/22.xyz"),
    ((np.array([641.067, 203.187, 213]), (72, -33, -90)), "/content/drive/MyDrive/clouds/23.xyz"),
    ((np.array([480.497, 203.187, 213]), (108, -33, -90)), "/content/drive/MyDrive/clouds/24.xyz"),
    ((np.array([350.593, 108.806, 213]), (144, -33, -90)), "/content/drive/MyDrive/clouds/25.xyz"),
    ((np.array([300.974, -43.905, 213]), (-180, -33, -90)), "/content/drive/MyDrive/clouds/26.xyz"),
    ((np.array([350.593, -196.616, 213]), (-144, -33, -90)), "/content/drive/MyDrive/clouds/27.xyz"),
    ((np.array([480.497, -290.997, 213]), (-108, -33, -90)), "/content/drive/MyDrive/clouds/28.xyz"),
    ((np.array([641.067, -290.997, 213]), (-72, -33, -90)), "/content/drive/MyDrive/clouds/29.xyz"),
    ((np.array([770.971, -196.616, 213]), (-36, -33, -90)), "/content/drive/MyDrive/clouds/30.xyz"),
    # Add more consecutive poses and point cloud file paths here
]



# Load point clouds from files and convert them to NumPy arrays
point_cloud_files = [pose[1] for pose in consecutive_poses]
point_clouds = load_and_convert_point_clouds(point_cloud_files)

# Create an empty list to store transformed point clouds
transformed_point_clouds = []

# Initialize the first point cloud
first_pcd = o3d.geometry.PointCloud()
first_pcd.points = o3d.utility.Vector3dVector(point_clouds[0])

# Loop through consecutive poses and apply transformations
for i, pose_pair in enumerate(consecutive_poses[1:]):
    # Convert Euler angles to radians for both poses
    roll1, pitch1, yaw1 = map(deg_to_rad, pose_pair[0][1])
    roll2, pitch2, yaw2 = map(deg_to_rad, consecutive_poses[i][0][1])

    # Compute rotation matrices for both poses
    R1 = euler_to_rotation(roll1, pitch1, yaw1)
    R2 = euler_to_rotation(roll2, pitch2, yaw2)

    # Compute inverse rotation matrices for both poses
    R_inv1 = inverse_rotation_matrix(R1)
    R_inv2 = inverse_rotation_matrix(R2)

    # Inverse translation vectors for both poses
    t1 = np.array(pose_pair[0][0])
    t2 = np.array(consecutive_poses[i][0][0])

    # Apply inverse transform to the second point cloud
    transformed_second_pcd = inverse_transform_point_cloud(point_clouds[i + 1], R_inv2, t2)

    # Add the transformed second point cloud to the first point cloud
    first_pcd.points.extend(o3d.utility.Vector3dVector(transformed_second_pcd))

# Convert the merged point cloud to a NumPy array
merged_point_cloud = np.asarray(first_pcd.points)

# Save merged point cloud to file (optional)
merged_pcd = o3d.geometry.PointCloud()
merged_pcd.points = o3d.utility.Vector3dVector(merged_point_cloud)
o3d.io.write_point_cloud("merged_point_cloud.xyz", merged_pcd)

print("Merged Point Cloud Shape:", merged_point_cloud.shape)

[Open3D WARNING] Read XYZ failed: unable to open file: /content/drive/MyDrive/clouds/3.xyz
[Open3D WARNING] Read XYZ failed: unable to open file: /content/drive/MyDrive/clouds/5.xyz
[Open3D WARNING] Read XYZ failed: unable to open file: /content/drive/MyDrive/clouds/18.xyz
Merged Point Cloud Shape: (4719, 3)


In [12]:

        # Visualize the transformed point cloud
        points = np.asarray(merged_pcd.points)


In [13]:
import plotly.graph_objects as go


In [14]:
fig = go.Figure(
    data=[
        go.Scatter3d(
            x=points[:,0], y=points[:,1], z=points[:,2],
            mode='markers',
            marker=dict(size=1, color='rgb(255, 0, 0)')
        )
    ],
    layout=dict(
        scene=dict(
            xaxis=dict(visible=False),
            yaxis=dict(visible=False),
            zaxis=dict(visible=False)
        )
    )
)
fig.show()

In [15]:
# Perform clustering on the merged point cloud
labels = np.array(merged_pcd.cluster_dbscan(eps=0.2, min_points=10))


# Get the unique labels and their counts
unique_labels, label_counts = np.unique(labels, return_counts=True)


# Find the label with the largest count
largest_cluster_label = unique_labels[np.argmax(label_counts)]


# Filter out points that belong to the largest cluster
largest_cluster_indices = np.where(labels == largest_cluster_label)[0]
largest_cluster_pcd = merged_pcd.select_by_index(largest_cluster_indices)

points = np.asarray(largest_cluster_pcd.points)


# New section - Vizualisation per section

In [16]:
import plotly.graph_objects as go

fig = go.Figure(
    data=[
        go.Scatter3d(
            x=points[:,0], y=points[:,1], z=points[:,2],
            mode='markers',
            marker=dict(size=3, color='rgb(255, 0, 0)')
        )
    ],
    layout=dict(
        scene=dict(
            xaxis=dict(visible=False),
            yaxis=dict(visible=False),
            zaxis=dict(visible=False)
        )
    )
)
fig.show()